routes/admin.php
<?php

Route::group(['namespace' => 'Backend','prefix' => 'admin', 'middleware' => ['auth','role:admin']], function() {



	Route::get('dashboard',[
	    'as'    =>  'admin.dashboard',
	    'uses'  =>  'DashboardController@dashboard'
	]);

	Route::get('dashboard/redirect/{id_project}',[
	    'as'    =>  'admin.dashboard.redirect',
	    'uses'  =>  'DashboardController@redirect'
	]);


	/**
	 * crud project
	 */
	Route::resource('projects','ProjectController');

	/**
	 * admin access
	 */
	Route::group(['prefix'=>'access','middleware'=>['role:admin','checkaccess'] ], function(){

		/**
		 * crud agent
		 */
		Route::resource('agents','AgentController');

		/**
		 * crud status
		 */
		Route::resource('status','StatusController');

		/**
		 * crud status
		 */
		Route::resource('kuotas','KuotaParameterController');
		/**
		 * template excel untuk responden
		 */
		Route::get('/kuotasGenerateExcelTemplate/','KuotaParameterController@generateExcelTemplate')->name('kuotas.generateexcel');
		Route::post('/kuotasImportExcel','KuotaParameterController@importExcel')->name('admin.kuotas.importExcel');

		/**
		 * crud respondens
		 */
		Route::resource('respondens','RespondenController');

		/**
		 * template excel untuk responden
		 */
		Route::get('/respondensGenerateExcelTemplate/','RespondenController@generateExcelTemplate')->name('respondens.generateexcel');

		/**
		 * import data staff dari excel
		 */
		Route::post('/respondensImportExcel','RespondenController@importExcel')->name('admin.respondens.importExcel');

		/**
		 * for assignment
		 */
		Route::get('/assignment/kuota','AssignmentController@kuota')->name('assignment.kuota');
		Route::get('/assignment/{id_kuota}','AssignmentController@index')->name('assignment.index');
		Route::get('/assignment/{id_agent}/{id_kuota}','AssignmentController@assign')->name('assignment.assign');
		Route::post('/assignment/{id_agent}/{id_kuota}','AssignmentController@assignProcess')->name('assignment.assignProcess');

		Route::get('/assignment/transfer/{id_agent}/{id_kuota}','AssignmentController@assignTransfer')->name('assignment.assignTransfer');
		Route::post('/assignment/transferProcess/{id_agent}/{id_kuota}','AssignmentController@transferProcess')->name('assignment.transferProcess');

		/**
		 * view responden
		 */
		Route::get('/assignment/viewResp/{id_agent}/{id_kuota}','AssignmentController@viewResp')->name('assignment.viewResp');
		Route::get('/assignment/viewRespDetail/{id_agent}/{id_kuota}/{id_resp}','AssignmentController@viewRespDetail')->name('assignment.viewRespDetail');
		Route::put('/assignment/viewRespDetailUpdate/{id_resp}','AssignmentController@viewRespDetailUpdate')->name('assignment.viewRespDetailUpdate');

		/**
		 * tabel perolehan
		 */
		Route::get('/perolehan/','PerolehanController@index')->name('perolehan.index');

		Route::get('/perolehanRespByKuota/{id_kuota}','PerolehanController@perolehanRespByKuota')->name('perolehan.perolehanRespByKuota');
		Route::get('/perolehanRespByStatus/{id_status}','PerolehanController@perolehanRespByStatus')->name('perolehan.perolehanRespByStatus');
		Route::get('/perolehanRespByAgent/{id_agent}','PerolehanController@perolehanRespByAgent')->name('perolehan.perolehanRespByAgent');
		//perolehan ajax
		Route::get('/perolehanRespByDate/','PerolehanController@perolehanRespByDate')->name('perolehan.perolehanRespByDate');
		Route::post('/perolehanRespByDateExport/','PerolehanController@perolehanRespByDateExport')->name('perolehan.perolehanRespByDateExport');

		// list rekaman
		Route::resource('listrekaman','ListRekamanController');

		Route::get('generateExcelTemplate/','ListRekamanController@generateExcelTemplate')->name('listrekaman.generateExcel');
		Route::post('importExcel/','ListRekamanController@importExcel')->name('listrekaman.importExcel');

		Route::get('ajaxListRespByStatus/{id_project}/{id_status}',[
		    'as'    =>  'admin.ajaxListRespByStatus',
		    'uses'  =>  'ListRekamanController@ajaxListRespByStatus'
		]);

		Route::resource('pesan','MessageController');

        /**
         * perolehan
         */
        Route::get('/perolehanbyTanggal','PerolehanController@perolehanByTanggal')->name('perolehan.byTanggal');

        Route::get('/perolehanbyKuota','PerolehanController@perolehanbyKuota')->name('perolehan.byKuota');

        Route::get('/perolehanbyStatus','PerolehanController@perolehanbyStatus')->name('perolehan.byStatus');

        Route::get('/perolehanbyAgent','PerolehanController@perolehanbyAgent')->name('perolehan.byAgent');


	});

	Route::get('respondens',[
	    'as'    =>  'api.respondens',
	    'uses'  =>  'RespondenController@respondensApi'
	]);

	Route::get('exportRespondens',[
	    'as'    =>  'exportRespondens',
	    'uses'  =>  'RespondenController@exportRespondens'
	]);

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::get('/playrekaman/','Backend\ListRekamanController@playrekaman')->name('listrekaman.playrekaman');

app/Models/Status.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Status extends Model
{
    protected $fillable = ['name'];
}

app/Http/Controllers/Backend/AgentController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Agents;
use Session;
use App\Http\Requests\AgentRequest;
use App\Role;
use App\User;

class AgentController extends Controller
{
    public function index() 
    {
    	$project = Session::get('session_project');

    	$agents = Agents::with('user')->where('project_id',$project->id)->get();

        // dd($agents->toArray());

    	return view('backend.agent.index',compact('agents','project'));

    }

    public function create()
    {
    	return view('backend.agent.create');
    }

    public function store(AgentRequest $request)
    {
    	$data['name']			=	$request->input('name');
    	$data['code']			=	$request->input('code');
    	$data['alamat']			=	$request->input('alamat');
    	$data['hp']				=	$request->input('hp');
    	$data['project_id']		=	Session::get('session_project')->id;
    	$agent = Agents::create($data);


    	/**
    	 * user agent
    	 */
    	$role = Role::where('name','agent')->first();

    	$user = new User();
    	$user->name 	= $request->input('name');
    	$user->email 	= $request->input('email');
    	$user->password = bcrypt($request->input('password'));
    	$user->save();


    	$user->attachRole($role);

    	$agent->user_id = $user->id;
    	$agent->save();

    	return redirect()->route('agents.index')->with('alert-success','Berhasil menyimpan data agent');

    }

    public function edit($id)
    {
    	$agent = Agents::with('user')->findOrFail($id);

    	return view('backend.agent.edit',compact('agent'));
    }

    public function update(AgentRequest $request,$id)
    {
    	$agent = Agents::findOrFail($id);

    	$agent->name 	= $request->input('name');
    	$agent->code 	= $request->input('code');
    	$agent->alamat 	= $request->input('alamat');
    	$agent->hp 		= $request->input('hp');
    	$agent->save();

    	$user = User::findOrFail($agent->user_id);

        if($request->has('email'))
        {
        	$user->email = $request->input('email');
        	$user->save();
        }

        if($request->has('password'))
        {
        	$user->password = bcrypt($request->input('password'));
        	$user->save();
        }

        return redirect()->route('agents.index')->with('alert-success','Berhasil mengupdate data agent');

    }

    public function destroy($id)
    {
    	Agents::destroy($id);
    }
}

app/Http/Controllers/Backend/AssignmentController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Agents;
use App\Models\Responden;
use App\Models\KuotaParameter;
use App\Models\LogResponden;
use App\Models\Status;
use Session;

class AssignmentController extends Controller
{
    public function kuota()
    {
        $project = Session::get('session_project');

        $kuotas = KuotaParameter::where('project_id',$project->id)->get();

        return view('backend.assignment.kuota',compact('kuotas'));
    }

    public function index($id_kuota)
    {

        $kuota = KuotaParameter::findOrFail($id_kuota);

    	$project = Session::get('session_project');

    	$agents = Agents::with('respondens')->where('project_id',$project->id)->get();					

    	return view('backend.assignment.index',compact('project','agents','kuota'));
    }

    public function assign($id_agent,$id_kuota)
    {
        $kuota = KuotaParameter::findOrFail($id_kuota);

    	$project = Session::get('session_project');

    	$agent = Agents::findOrFail($id_agent);

    	$respondens = Responden::with('kuota')
                                ->where('project_id',$project->id)
    							->whereNull('agent_id')
    							->where('last_status_id',99)
                                ->where('is_lock',false)
                                ->where('kuota_parameter_id',$kuota->id)
    							->get();


    	return view('backend.assignment.assign',compact('agent','respondens','kuota'));
    }

    public function assignProcess(Request $request,$id_agent,$id_kuota)
    {
    	$agent = Agents::findOrFail($id_agent);
        $kuota = KuotaParameter::findOrFail($id_kuota);

    	$respondens = $request->input('respondens');

    	if(count($respondens))
    	{
    		foreach ($respondens as $id_responden ) {
    			// $responden isinya id responden	
    			$responden = Responden::findOrFail($id_responden);
    			$responden->agent_id = $agent->id;
    			$responden->save();		
    		}

    		return redirect()->route('assignment.index',$kuota->id)->with('alert-success','Berhasil mengassignt responden');
    	}else{
    		return redirect()->route('assignment.index',$kuota->id)->with('alert-gagal','Gagal  mengassignt responden');
    	}



    }

    public function assignTransfer($id_agent,$id_kuota)
    {
    	$project = Session::get('session_project');

    	$agent = Agents::findOrFail($id_agent);

        $kuota = KuotaParameter::findOrFail($id_kuota);

    	$respondens = Responden::with('status')->where('project_id',$project->id)
    							->where('agent_id',$agent->id)
    							->where('is_lock',false)
    							->where('last_status_id',99)
                                ->where('kuota_parameter_id',$kuota->id)
    							->get();

    	$list_agents = 	Agents::where('id','<>',$agent->id)
                                ->where('project_id',$project->id)     
    							->pluck('name','id');						

    	return view('backend.assignment.transfer',compact('project','agents','agent','respondens','list_agents','kuota'));							

    }

    public function transferProcess(Request $request,$id_agent,$id_kuota)
    {
    	$agent = Agents::findOrFail($id_agent);

    	$agent_tujuan = $request->input('agent_id');


    	$respondens = $request->input('respondens');

        $kuota = KuotaParameter::findOrFail($id_kuota);

    	if(count($respondens))
    	{
    		foreach ($respondens as $id_responden ) {
    			// $responden isinya id responden	
    			$responden = Responden::findOrFail($id_responden);
    			$responden->agent_id = $agent_tujuan;
    			$responden->save();		
    		}

    		return redirect()->route('assignment.index', $kuota->id)->with('alert-success','Berhasil trasfer responden');
    	}else{
    		return redirect()->route('assignment.index',$kuota->id)->with('alert-gagal','Gagal  transfer responden');
    	}
    }

    public function viewResp($id_agent,$id_kuota)
    {
        $agent = Agents::findOrFail($id_agent);

        $project = Session::get('session_project');

        $kuota = KuotaParameter::findOrFail($id_kuota);


        $respondens = Responden::with(['kuota','status'])
                                ->where('project_id',$project->id)
                                ->where('agent_id',$agent->id)
                                ->where('is_lock',false)
                                ->where('kuota_parameter_id',$kuota->id)
                                ->get();

        return view('backend.assignment.viewResp',compact('agent','project','kuota','respondens'));                          
                                
    }

    public function viewRespDetail($id_agent,$id_kuota,$id_resp)
    {
        $project = Session::get('session_project');

        $kuota = KuotaParameter::findOrFail($id_kuota);

        $agent = Agents::findOrFail($id_agent);

        $respondent = Responden::with(['kuota','status'])->findOrFail($id_resp);

        $list_status = Status::pluck('name','id');

        return view('backend.assignment.viewRespDetail',compact('agent','project','kuota','respondent','list_status'));   


    }

    public function viewRespDetailUpdate(Request $request,$id_resp)
    {
        $project = Session::get('session_project');


        $respondent = Responden::findOrFail($id_resp);
        $respondent->last_status_id = $request->input('status_id');
        $respondent->save();
        // dd($respondent->toArray());    
        /**
         * get log terakhir
         */
        // $logs = LogResponden::where('responden_id',$respondent->id)->delete();
        $last_log  = LogResponden::where('responden_id',$respondent->id)
                                  ->orderBy('id','desc')
                                  ->first();

        if(!is_null($last_log))
        {
            $new_log                = new LogResponden();
            $new_log->responden_id  = $last_log->responden_id;
            $new_log->status_id     = $request->input('status_id');
            $new_log->nomor_hp      = $last_log->nomor_hp;
            $new_log->tgl_reschedule  = $last_log->tgl_reschedule;
            $new_log->agent_name   = $last_log->agent_name;
            $new_log->save();

        }                        

                                  // dd($respondent->toArray());

        return  redirect()->route('assignment.viewResp', [$respondent->agent_id,$respondent->kuota_parameter_id] )->with('alert-success','Rubah Status Berhasil');  
        
        
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Project;
use Session;

class DashboardController extends Controller
{
    public function dashboard()
    {

    	$projects = Project::all();

    	return view('backend.dashboard.dashboard',compact('projects'));
    }


    public function redirect(Request $request,$id)
    {
    	$project = Project::findOrFail($id);

    	$request->session()->put('session_project', $project);

    	return redirect('/admin/access/agents');
    }

    

    
}

app/Http/Controllers/Backend/MessageController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Message;

class MessageController extends Controller
{
    public function index()
    {
    	$messages = Message::with('agent')->where('is_read',false)->orderBy('created_at','desc')->get();

    	return view('backend.message.index',compact('messages'));

    }

    public function edit($id_pesan)
    {
    	$message = Message::findOrFail($id_pesan);
    	$message->is_read = true;
    	$message->save();

    	 return redirect()->route('pesan.index')->with('alert-success','Masalah berhasil ditangani');
    }
}

resources/views/backend/status/create.blade.php
@extends('layouts.app')


@section('content')
<div class="container-fluid">
    <div class="row">
        
        @include('backend.partials.sidebar')

        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">
                  Create Status
                </div>

                <div class="panel-body">
                    
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('status.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nama</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Save
                                </button>

                            </div>
                        </div>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/backend/status/edit.blade.php
@extends('layouts.app')


@section('content')
<div class="container-fluid">
    <div class="row">
        
        @include('backend.partials.sidebar')

        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">
                  Edit Status
                </div>

                <div class="panel-body">
                    
                     {!!  Form::model($status, array('method' => 'put', 'route' => array('status.update', $status->id), 'files'=> false,'class'=>'form-horizontal')) !!}

                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nama</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ $status->name }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Update
                                </button>

                            </div>
                        </div>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/backend/status/index.blade.php
@extends('layouts.app')


@section('css')
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css">
<link rel="stylesheet" href="{{ asset('css/sweetalert2.css') }}">
@endsection


@section('content')
<div class="container-fluid">
    
    <div class="row">
        <div class="col-md-12">

          {{-- Untuk Pesan Sukses --}}
          @if(Session::has('alert-success'))
              <div class="alert alert-success">
                    {{ Session::get('alert-success') }}
                </div>
          @endif

        </div>
      </div>

    <div class="row">
        
        @include('backend.partials.sidebar')

        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">
                  List Status
                  <a href="{{ route('status.create') }}" class="btn btn-primary">Tambah Status</a>
                </div>

                <div class="panel-body">
                    
                    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>Nama</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        
                        <tbody>
                            
                            @foreach($statuses as $status)
                                <tr>
                                    <td>{{ $status->name }}</td>
                                    <td>
                                        <div class="btn-group" role="group" aria-label="...">
                                          <a href="{{ route('status.edit',$status->id) }}" class="btn btn-success">Edit</a>
                                          <a href="#" data-target="{{ route('status.destroy', [$status->id]) }}" class="btn btn-danger confirmation" onclick="hapusData(this)">Hapus</a>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            
                        </tbody>
                    </table>

                </div>
                
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
<script src="{{ asset('js/sweetalert2.min.js') }}"></script>
<script src="{{ asset('js/confirm.js') }}"></script>
<script>
  $(document).ready(function() {
    $('#example').DataTable();
} );
</script>
@endsection